Repository jrtapsell/MetabaseAutoCovid, pull requests merged in 2020-04, with the labels that each got.

#15 Fixed codacy markdown issues
  README.md
Labels: Codacy

#18 Added Bandit config file
  bandit.yml
Labels: Codacy

#19 Quoted the entrypoint file name to solve issues
  entrypoint.sh
Labels: codacy

#21 Add a Gitter chat badge to README.md
  README.md
Labels: documentation

#22 Add Gitter badge
  README.md
Labels: documentation

#27 Trying to fix the release action
  .github/workflows/build.yaml
Labels: bug

#29 Fixed release action referring to github repo for docker hub login
  .github/workflows/build.yaml
Labels: bug

#30 Updated the README to add links and order the badges
  README.md
Labels: documentation

#32 Update README.md
  README.md
Labels: documentation
